Documentation:
  Enabled: false

AllCops:
  Exclude:
    - config/initializers/rails_admin_pg_arrays.rb
    - db/**/*

Metrics/AbcSize:
  Enabled: false
Metrics/BlockNesting:
  Max: 4
Metrics/ClassLength:
  CountComments: false  # count full line comments?
  Max: 200
Metrics/ModuleLength:
  CountComments: false  # count full line comments?
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 15
Metrics/MethodLength:
  CountComments: false  # count full line comments?
  Max: 35
Metrics/ParameterLists:
  Max: 5
  CountKeywordArgs: true
Metrics/PerceivedComplexity:
  Max: 12
Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Enabled: false
Layout/SpaceBeforeFirstArg:
  Exclude:
    - app/views/api/**/**/*


Style/HashSyntax:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false