version: "3.9"
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
    ports:
      - "5444:5433"
      - "5443:5432"
  web:
    image: docker.gonzaloy.com/pspcode:0.0.2
    ports:
      - "3000:3000"
    depends_on:
      - db
